//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace solar_plan_2
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    public partial class Events
    {
        [Key]
        [HiddenInput(DisplayValue = false)]
        public int ID { get; set; }
        [Display(Name = "Название события")]
        [Required]
        [MaxLength(200)]
        public string Name_Event { get; set; }
        [Display(Name = "Описание события")]
        [Required]
        public string Subscr_Event { get; set; }
        [Display(Name = "Начало события")]
        [Required]
        [DataType(DataType.DateTime)]
       
        public System.DateTime Start_Date { get; set; }
        [Display(Name = "Окончание события")]
        [Required]
        [DataType(DataType.DateTime)]
       
        public System.DateTime End_Date { get; set; }
        [Display(Name = "Будет отложено??")]
        [Required]
        public bool IsDeffered { get; set; }
    }
}
